name: e_commerce_app_home_task_by_apac_flutter_app
description: A Flutter project for APAC's candidate assesment.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

#---------------- PACKAGES -------------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.3

  # Icons
  cupertino_icons: ^1.0.2

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific

  #------------ ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #------------- LOCAL ASSETS -----------#

  assets:
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/
    - assets/logos/

  #------------- LOCAL FONTS -----------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
